name: StatMasterX
version: '${version}'
main: pl.syntaxdevteam.StatMasterX
api-version: '1.20'
authors: [SyntaxDevTeam]
description: Advanced Player Statistics and Achievements
website: https://github.com/SyntaxDevTeam
# This sets PlaceholderAPI as an optional dependency for your plugin.
depend: []
softdepend: [PlaceholderAPI, Vault]
